apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-webdemo-app  ####
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/joaquingraziano/argocd.git ####
    targetRevision: HEAD
    path: dev/app/ ####
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev-webdemo   ####

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-webdemo-app  ####
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/joaquingraziano/argocd.git  ####
    targetRevision: HEAD
    path: prod/app/ ####
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod-webdemo   ####

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-webdemo-app  ####
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/joaquingraziano/argocd.git ####
    targetRevision: HEAD
    path: staging/app/ ####
  destination: 
    server: https://kubernetes.default.svc
    namespace: preprod-webdemo   ####

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true