apiVersion: v1
kind: Service
metadata:
  name: webdemo-service
spec:
  selector:
    app: webdemo
  type: NodePort # Puedes cambiar esto según tus necesidades de red
  ports:
    - name: http
      port: 80 # Puedes cambiar esto según las necesidades de tu aplicación
      targetPort: 80 # Puedes cambiar esto según las necesidades de tu aplicación
