apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-webdemo-app  ####
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/joaquingraziano/argocd.git ####
    targetRevision: HEAD
    path: Dev/app/ ####
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev-myshoppingweb   ####

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true