apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-webdemo-app  ####
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Jiolloker/manifest-eks.git ####
    targetRevision: HEAD
    path: prod/app/ ####
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod-myshoppingweb   ####

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true